/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgot-password` | `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/registration` | `/registration`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/review` | `/review`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/success` | `/success`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/active-ride` | `/active-ride`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/ride-completed` | `/ride-completed`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/forgot-password` | `/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/registration` | `/registration`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/review` | `/review`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/success` | `/success`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/active-ride` | `/active-ride`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/ride-completed` | `/ride-completed`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/forgot-password${`?${string}` | `#${string}` | ''}` | `/forgot-password${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/registration${`?${string}` | `#${string}` | ''}` | `/registration${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/review${`?${string}` | `#${string}` | ''}` | `/review${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/success${`?${string}` | `#${string}` | ''}` | `/success${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/active-ride${`?${string}` | `#${string}` | ''}` | `/active-ride${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/ride-completed${`?${string}` | `#${string}` | ''}` | `/ride-completed${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgot-password` | `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/registration` | `/registration`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/review` | `/review`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/success` | `/success`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/active-ride` | `/active-ride`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/ride-completed` | `/ride-completed`; params?: Router.UnknownInputParams; };
    }
  }
}
